## libraries
library(cowplot)
library(DESeq2)
library(dplyr)
library(edgeR)
library(ggplot2)
library(ggrepel)
library(gridExtra)
library(patchwork)
library(pheatmap)
library(rafalib)
library(reshape2)
library(scales)
library(tibble)
mypar()

## functions
source("DESeqCalculation.R")
source("gabel.function.R")
source("logofMeans.R")
source("overlay.gabel.function.R")
source("overlay.mCA.R")
source("overlap_wrappers.R")
source("plot2plots.R")